# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec6bb7871919f742055a598f3e4ac49e92991bc10da00870ff49226cd542f44ba447cf1f6053e5620a1ee0f4e1e3725ba638cbd4ca4534e71e5397be458b7d9

test:
  secret_key_base: b3c1696ffdb802e9f79197d92ac51c946f3b1ec935c266c17ab0bacd7a694c0966c757d30832731ad32ab2b660612abada54730c8a59bbab09f7145e42b9c276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
